image: maven:3.6-jdk-11

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn install -B

test:
  stage: test
  script:
    - mvn test -B

deploy :
  stage: deploy
  script:
    - /bin/echo "Deploing ... "
